apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base
  - vllm-servicemonitor.yaml
  - monitoring/vllm-alerts.yaml
patches:
  - path: secret-env-patch.yaml
  - path: vllm-runtime-patch.yaml
  - path: rollback-test-patch.yaml

namePrefix: dev-
namespace: vllm-dev
