apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base
patches:
  - path: secret-env-patch.yaml
  - path: vllm-runtime-patch.yaml

namePrefix: dev-
namespace: vllm-dev
