apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  template:
    spec:
      containers:
        - name: vllm
          image: ghcr.io/sachin001234/vllm-platform:rollback-test-invalid
