apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  template:
    spec:
      nodeSelector:
        accelerator: nvidia-gpu
      containers:
        - name: vllm
          resources:
            limits:
              nvidia.com/gpu: 1
