apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base

namePrefix: prod-
namespace: vllm-prod

patches:
  - path: gpu-patch.yaml
  - path: secret-env-patch.yaml
